import { ArrowRight, Layers3, ListChecks, Scissors } from 'lucide-react'
import { Link } from 'react-router-dom'
import ClothingImage from '../components/ClothingImage'
import { ErrorState, LoadingState } from '../components/States'
import { useResource } from '../hooks/useResource'
import { categoriesApi, clothingApi, outfitItemsApi, outfitsApi } from '../services/wardrobe'

export default function HomePage() {
  const clothing = useResource(clothingApi.list)
  const outfits = useResource(outfitsApi.list)
  const outfitItems = useResource(outfitItemsApi.list)
  const categories = useResource(categoriesApi.list)
  const categoryName = (categoryId: number) => categories.data?.find((item) => item.category_id === categoryId)?.name ?? 'Uncategorised'

  return <main>
    <section className="home-hero" aria-labelledby="home-title"><div className="hero-content"><span className="eyebrow">A considered closet</span><h1 id="home-title">Your wardrobe,<span>reimagined.</span></h1><p>Bring every piece into view. Keep your collection considered, your combinations close, and your everyday style unmistakably yours.</p><Link className="button-primary" to="/app/wardrobe">Explore My Wardrobe <ArrowRight size={15} aria-hidden="true" /></Link></div><span className="hero-note">A more thoughtful way to get dressed</span></section>
    <section className="home-section" id="approach"><div className="section-heading"><div><span className="eyebrow">Designed around what you own</span><h2>Less searching.<br />More wearing.</h2></div><p>A quiet place for the pieces you reach for, the combinations you love, and the details that make getting dressed feel effortless.</p></div><div className="feature-band"><article className="feature-item"><span className="feature-icon"><Layers3 size={18} aria-hidden="true" /></span><h3>One considered collection</h3><p>Keep clothing and categories together, with useful details close at hand.</p></article><article className="feature-item"><span className="feature-icon"><ListChecks size={18} aria-hidden="true" /></span><h3>See what you reach for</h3><p>Search and filter your collection to find the right piece without the rummage.</p></article><article className="feature-item"><span className="feature-icon"><Scissors size={18} aria-hidden="true" /></span><h3>Keep outfits in view</h3><p>Save combinations from the clothing already in your wardrobe.</p></article></div></section>
    <section className="home-section preview-section" id="collection"><div className="section-heading"><div><span className="eyebrow">Your collection</span><h2>Pieces with a place.</h2></div><Link className="text-link" to="/app/wardrobe">View wardrobe <ArrowRight size={14} aria-hidden="true" /></Link></div>{clothing.loading ? <LoadingState label="Loading your collection" /> : clothing.error ? <ErrorState message={clothing.error.message} onRetry={clothing.retry} /> : clothing.data?.length ? <div className="preview-grid">{clothing.data.slice(0,3).map((item) => <article className="preview-clothing" key={item.clothing_id}><Link className="preview-image" to={`/app/wardrobe/${item.clothing_id}`} aria-label={`View ${item.name}`}><ClothingImage src={item.image_url} alt={item.name} /></Link><div className="preview-meta"><div><h3>{item.name}</h3><p>{categoryName(item.category_id)}</p></div><span>{item.color || item.size || ''}</span></div></article>)}</div> : <div className="preview-message">No clothing items yet.</div>}</section>
    <section className="home-section" id="outfit-edit"><div className="section-heading"><div><span className="eyebrow">Made from your wardrobe</span><h2>Outfits, kept together.</h2></div><Link className="text-link" to="/app/outfits">Explore outfits <ArrowRight size={14} aria-hidden="true" /></Link></div>{outfits.loading || outfitItems.loading || clothing.loading ? <LoadingState label="Loading saved outfits" /> : outfits.error || outfitItems.error || clothing.error ? <ErrorState message={(outfits.error || outfitItems.error || clothing.error)?.message ?? 'Outfits could not be loaded.'} onRetry={() => { outfits.retry(); outfitItems.retry(); clothing.retry() }} /> : outfits.data?.length ? <div className="outfit-preview-grid">{outfits.data.slice(0,2).map((outfit) => { const pieces = (outfitItems.data ?? []).filter((item) => item.outfit_id === outfit.outfit_id).map((item) => clothing.data?.find((piece) => piece.clothing_id === item.clothing_id)?.name).filter((name): name is string => Boolean(name)); return <article className="outfit-preview" key={outfit.outfit_id}><h3>{outfit.name}</h3><p>{outfit.description || 'A saved combination from your collection.'}</p><div className="outfit-piece-list">{pieces.length ? pieces.slice(0,4).map((piece,index) => <span className="outfit-piece" key={`${piece}-${index}`}>{piece}</span>) : <span className="outfit-piece">No linked pieces</span>}</div></article>})}</div> : <div className="preview-message">No saved outfits yet.</div>}</section>
  </main>
}